### ISSUE TITLE
The joker menu does not appear

### ISSUE THREAD

**Issue by Septembers** [Javierko/DeathrunCSGO#3]
Hey. The joker menu at the beginning of the round does not always appear automatically. Need to somehow fix it.

**Comment by Javierko** [comment]
I made fix for this, you can try it using version [2.0.5](https://github.com/Javierko/DeathrunCSGO/commit/edb8d54f1e0361b592517131d0cf65042c37b43c).

**Comment by Septembers** [comment]
> I made fix for this, you can try it using version [2.0.5](https://github.com/Javierko/DeathrunCSGO/commit/edb8d54f1e0361b592517131d0cf65042c37b43c).

L 03/01/2019 - 18:49:00: [SM] Exception reported: Menu handle 0 is invalid (error 4)
L 03/01/2019 - 18:49:00: [SM] Blaming: Deathrun.smx
L 03/01/2019 - 18:49:00: [SM] Call stack trace:
L 03/01/2019 - 18:49:00: [SM]   [0] Menu.Display
L 03/01/2019 - 18:49:00: [SM]   [1] Line 134, deathrun/events.sp::Event_RoundStart
L 03/01/2019 - 18:49:11: [SM] Exception reported: Menu handle 0 is invalid (error 4)
L 03/01/2019 - 18:49:11: [SM] Blaming: Deathrun.smx
L 03/01/2019 - 18:49:11: [SM] Call stack trace:
L 03/01/2019 - 18:49:11: [SM]   [0] Menu.Display
L 03/01/2019 - 18:49:11: [SM]   [1] Line 134, deathrun/events.sp::Event_RoundStart

**Comment by Javierko** [comment]
Should be fixed in [2.0.5 fix](https://github.com/Javierko/DeathrunCSGO/commit/2893aaba4cbbe98baf7a93059ee2b80b020e9d91)

**Comment by Septembers** [comment]
> Should be fixed in [2.0.5 fix](https://github.com/Javierko/DeathrunCSGO/commit/2893aaba4cbbe98baf7a93059ee2b80b020e9d91)

L 03/01/2019 - 23:57:01: [SM] Exception reported: Handle 826f06b2 is invalid (error 1)
L 03/01/2019 - 23:57:01: [SM] Blaming: Deathrun.smx
L 03/01/2019 - 23:57:01: [SM] Call stack trace:
L 03/01/2019 - 23:57:01: [SM]   [0] CloseHandle
L 03/01/2019 - 23:57:01: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart

players say that the joker menu does not appear, and the command does not work.

**Comment by Septembers** [comment]
L 03/02/2019 - 18:55:34: Info (map "deathrun_halloween") (file "errors_20190302.log")
L 03/02/2019 - 18:55:34: [SM] Exception reported: Handle 8cd00db8 is invalid (error 3)
L 03/02/2019 - 18:55:34: [SM] Blaming: Deathrun.smx
L 03/02/2019 - 18:55:34: [SM] Call stack trace:
L 03/02/2019 - 18:55:34: [SM]   [0] CloseHandle
L 03/02/2019 - 18:55:34: [SM]   [1] Line 58, deathrun/menu.sp::mJoker
L 03/02/2019 - 18:55:39: [SM] Exception reported: Handle 8cd00db8 is invalid (error 1)
L 03/02/2019 - 18:55:39: [SM] Blaming: Deathrun.smx
L 03/02/2019 - 18:55:39: [SM] Call stack trace:
L 03/02/2019 - 18:55:39: [SM]   [0] CloseHandle
L 03/02/2019 - 18:55:39: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/02/2019 - 18:57:28: [SM] Exception reported: Handle 8cd00db8 is invalid (error 1)
L 03/02/2019 - 18:57:28: [SM] Blaming: Deathrun.smx
L 03/02/2019 - 18:57:28: [SM] Call stack trace:
L 03/02/2019 - 18:57:28: [SM]   [0] CloseHandle
L 03/02/2019 - 18:57:28: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart

**Comment by m1000rr** [comment]
I quess this wasn't fixed yet? Have tried latest version and getting these errors:


L 03/07/2019 - 01:27:55: SourceMod error session started
L 03/07/2019 - 01:27:55: Info (map "workshop/328517660/deathrun_holyshit_v2") (file "errors_20190307.log")
L 03/07/2019 - 01:27:55: [SM] Exception reported: Handle 33600de is invalid (error 1)
L 03/07/2019 - 01:27:55: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:27:55: [SM] Call stack trace:
L 03/07/2019 - 01:27:55: [SM]   [0] CloseHandle
L 03/07/2019 - 01:27:55: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:29:38: [SM] Exception reported: Menu handle 33600de is invalid (error 1)
L 03/07/2019 - 01:29:38: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:29:38: [SM] Call stack trace:
L 03/07/2019 - 01:29:38: [SM]   [0] Menu.Display
L 03/07/2019 - 01:29:38: [SM]   [1] Line 183, C:\Users\User\Desktop\Deathrun\Deathrun.sp::Command_Joker
L 03/07/2019 - 01:30:48: [SM] Exception reported: Handle 33600de is invalid (error 1)
L 03/07/2019 - 01:30:48: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:30:48: [SM] Call stack trace:
L 03/07/2019 - 01:30:48: [SM]   [0] CloseHandle
L 03/07/2019 - 01:30:48: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:31:26: [SM] Exception reported: Handle 33600de is invalid (error 1)
L 03/07/2019 - 01:31:26: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:31:26: [SM] Call stack trace:
L 03/07/2019 - 01:31:26: [SM]   [0] CloseHandle
L 03/07/2019 - 01:31:26: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:34:42: [SM] Exception reported: Handle 33600de is invalid (error 1)
L 03/07/2019 - 01:34:42: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:34:42: [SM] Call stack trace:
L 03/07/2019 - 01:34:42: [SM]   [0] CloseHandle
L 03/07/2019 - 01:34:42: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:36:00: [SM] Exception reported: Handle 33600de is invalid (error 1)
L 03/07/2019 - 01:36:00: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:36:00: [SM] Call stack trace:
L 03/07/2019 - 01:36:00: [SM]   [0] CloseHandle
L 03/07/2019 - 01:36:00: [SM]   [1] Line 115, C:\Users\User\Desktop\Deathrun\Deathrun.sp::OnMapEnd
L 03/07/2019 - 01:36:00: Error log file session closed.
L 03/07/2019 - 01:37:05: SourceMod error session started
L 03/07/2019 - 01:37:05: Info (map "workshop/368596247/deathrun_classic") (file "errors_20190307.log")
L 03/07/2019 - 01:37:05: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:37:05: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:37:05: [SM] Call stack trace:
L 03/07/2019 - 01:37:05: [SM]   [0] CloseHandle
L 03/07/2019 - 01:37:05: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:38:34: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:38:34: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:38:34: [SM] Call stack trace:
L 03/07/2019 - 01:38:34: [SM]   [0] CloseHandle
L 03/07/2019 - 01:38:34: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:41:49: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:41:49: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:41:49: [SM] Call stack trace:
L 03/07/2019 - 01:41:49: [SM]   [0] CloseHandle
L 03/07/2019 - 01:41:49: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:45:04: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:45:04: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:45:04: [SM] Call stack trace:
L 03/07/2019 - 01:45:04: [SM]   [0] CloseHandle
L 03/07/2019 - 01:45:04: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:48:19: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:48:19: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:48:19: [SM] Call stack trace:
L 03/07/2019 - 01:48:19: [SM]   [0] CloseHandle
L 03/07/2019 - 01:48:19: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:51:34: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:51:34: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:51:34: [SM] Call stack trace:
L 03/07/2019 - 01:51:34: [SM]   [0] CloseHandle
L 03/07/2019 - 01:51:34: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:52:45: [SM] Exception reported: Handle 53e00ee is invalid (error 1)
L 03/07/2019 - 01:52:45: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:52:45: [SM] Call stack trace:
L 03/07/2019 - 01:52:45: [SM]   [0] CloseHandle
L 03/07/2019 - 01:52:45: [SM]   [1] Line 115, C:\Users\User\Desktop\Deathrun\Deathrun.sp::OnMapEnd
L 03/07/2019 - 01:52:46: Error log file session closed.
L 03/07/2019 - 01:54:04: SourceMod error session started
L 03/07/2019 - 01:54:04: Info (map "cs_office") (file "errors_20190307.log")
L 03/07/2019 - 01:54:04: [SM] Exception reported: Handle 9700117 is invalid (error 1)
L 03/07/2019 - 01:54:04: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:54:04: [SM] Call stack trace:
L 03/07/2019 - 01:54:04: [SM]   [0] CloseHandle
L 03/07/2019 - 01:54:04: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:54:37: [SM] Exception reported: Handle 9700117 is invalid (error 1)
L 03/07/2019 - 01:54:37: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:54:37: [SM] Call stack trace:
L 03/07/2019 - 01:54:37: [SM]   [0] CloseHandle
L 03/07/2019 - 01:54:37: [SM]   [1] Line 115, C:\Users\User\Desktop\Deathrun\Deathrun.sp::OnMapEnd
L 03/07/2019 - 01:54:37: Error log file session closed.
L 03/07/2019 - 01:55:42: SourceMod error session started
L 03/07/2019 - 01:55:42: Info (map "workshop/328830229/deathrun_cb_egypt_csgo_v1") (file "errors_20190307.log")
L 03/07/2019 - 01:55:42: [SM] Exception reported: Handle a58011c is invalid (error 1)
L 03/07/2019 - 01:55:42: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:55:42: [SM] Call stack trace:
L 03/07/2019 - 01:55:42: [SM]   [0] CloseHandle
L 03/07/2019 - 01:55:42: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
L 03/07/2019 - 01:56:10: [SM] Exception reported: Menu handle a58011c is invalid (error 1)
L 03/07/2019 - 01:56:10: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:56:10: [SM] Call stack trace:
L 03/07/2019 - 01:56:10: [SM]   [0] Menu.Display
L 03/07/2019 - 01:56:10: [SM]   [1] Line 183, C:\Users\User\Desktop\Deathrun\Deathrun.sp::Command_Joker
L 03/07/2019 - 01:57:27: [SM] Exception reported: Handle a58011c is invalid (error 1)
L 03/07/2019 - 01:57:27: [SM] Blaming: Deathrun.smx
L 03/07/2019 - 01:57:27: [SM] Call stack trace:
L 03/07/2019 - 01:57:27: [SM]   [0] CloseHandle
L 03/07/2019 - 01:57:27: [SM]   [1] Line 126, deathrun/events.sp::Event_RoundStart
``

**Comment by Javierko** [comment]
Sorry for no activity, was very busy.

Here is [fix](https://github.com/Javierko/DeathrunCSGO/commit/82870150f8e280c87abfc6eca1f2e1756b9a55ec)

**Comment by m1000rr** [comment]
Just tested and getting these now: 

> L 03/08/2019 - 08:13:53: SourceMod error session started
L 03/08/2019 - 08:13:53: Info (map "workshop/368596247/deathrun_classic") (file "errors_20190308.log")
L 03/08/2019 - 08:13:53: [SM] Exception reported: Handle 18200f9 is invalid (error 1)
L 03/08/2019 - 08:13:53: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:13:53: [SM] Call stack trace:
L 03/08/2019 - 08:13:53: [SM]   [0] CloseHandle
L 03/08/2019 - 08:13:53: [SM]   [1] Line 127, deathrun/events.sp::Event_RoundStart
L 03/08/2019 - 08:14:30: [SM] Exception reported: Menu handle 18200f9 is invalid (error 3)
L 03/08/2019 - 08:14:30: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:14:30: [SM] Call stack trace:
L 03/08/2019 - 08:14:30: [SM]   [0] Menu.Display
L 03/08/2019 - 08:14:30: [SM]   [1] Line 184, C:\Users\User\Desktop\Deathrun\Deathrun.sp::Command_Joker
L 03/08/2019 - 08:15:41: [SM] Exception reported: Menu handle 18200f9 is invalid (error 3)
L 03/08/2019 - 08:15:41: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:15:41: [SM] Call stack trace:
L 03/08/2019 - 08:15:41: [SM]   [0] Menu.Display
L 03/08/2019 - 08:15:41: [SM]   [1] Line 184, C:\Users\User\Desktop\Deathrun\Deathrun.sp::Command_Joker
L 03/08/2019 - 08:16:41: [SM] Exception reported: Menu handle 18200f9 is invalid (error 3)
L 03/08/2019 - 08:16:41: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:16:41: [SM] Call stack trace:
L 03/08/2019 - 08:16:41: [SM]   [0] Menu.Display
L 03/08/2019 - 08:16:41: [SM]   [1] Line 184, C:\Users\User\Desktop\Deathrun\Deathrun.sp::Command_Joker
L 03/08/2019 - 08:16:58: [SM] Exception reported: Handle 18200f9 is invalid (error 3)
L 03/08/2019 - 08:16:58: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:16:58: [SM] Call stack trace:
L 03/08/2019 - 08:16:58: [SM]   [0] CloseHandle
L 03/08/2019 - 08:16:58: [SM]   [1] Line 181, deathrun/events.sp::Event_RoundEnd
L 03/08/2019 - 08:17:08: [SM] Exception reported: Handle 18200f9 is invalid (error 1)
L 03/08/2019 - 08:17:08: [SM] Blaming: Deathrun.smx
L 03/08/2019 - 08:17:08: [SM] Call stack trace:
L 03/08/2019 - 08:17:08: [SM]   [0] CloseHandle
L 03/08/2019 - 08:17:08: [SM]   [1] Line 127, deathrun/events.sp::Event_RoundStart
L 03/08/2019 - 08:18:31: [SM] Exception reported: Handle 18200f9 is invalid (error 1)

**Comment by Javierko** [comment]
[Should be fix](https://github.com/Javierko/DeathrunCSGO/commit/2c6e2a453ecb19bb8d3145d79ea989196a12b4a7)

**Comment by m1000rr** [comment]
The menu does apear now but it's showing wrong options. Here is the log:

> L 03/09/2019 - 21:33:59: SourceMod error session started
L 03/09/2019 - 21:33:59: Info (map "workshop/368596247/deathrun_classic") (file "errors_20190309.log")
L 03/09/2019 - 21:33:59: [SM] Exception reported: Handle 20a00f6 is invalid (error 3)
L 03/09/2019 - 21:33:59: [SM] Blaming: Deathrun.smx
L 03/09/2019 - 21:33:59: [SM] Call stack trace:
L 03/09/2019 - 21:33:59: [SM]   [0] CloseHandle
L 03/09/2019 - 21:33:59: [SM]   [1] Line 66, deathrun/menu.sp::mJoker
L 03/09/2019 - 21:34:13: [SM] Exception reported: Handle 22200f6 is invalid (error 3)
L 03/09/2019 - 21:34:13: [SM] Blaming: Deathrun.smx
L 03/09/2019 - 21:34:13: [SM] Call stack trace:
L 03/09/2019 - 21:34:13: [SM]   [0] CloseHandle
L 03/09/2019 - 21:34:13: [SM]   [1] Line 66, deathrun/menu.sp::mJoker
L 03/09/2019 - 21:34:28: [SM] Exception reported: Handle 23d00f6 is invalid (error 3)
L 03/09/2019 - 21:34:28: [SM] Blaming: Deathrun.smx
L 03/09/2019 - 21:34:28: [SM] Call stack trace:
L 03/09/2019 - 21:34:28: [SM]   [0] CloseHandle
L 03/09/2019 - 21:34:28: [SM]   [1] Line 66, deathrun/menu.sp::mJoker
L 03/09/2019 - 21:34:46: [SM] Exception reported: Handle 25500f6 is invalid (error 3)
L 03/09/2019 - 21:34:46: [SM] Blaming: Deathrun.smx
L 03/09/2019 - 21:34:46: [SM] Call stack trace:
L 03/09/2019 - 21:34:46: [SM]   [0] CloseHandle
L 03/09/2019 - 21:34:46: [SM]   [1] Line 66, deathrun/menu.sp::mJoker
L 03/09/2019 - 21:35:16: [SM] Exception reported: Handle 27a00f6 is invalid (error 3)
L 03/09/2019 - 21:35:16: [SM] Blaming: Deathrun.smx
L 03/09/2019 - 21:35:16: [SM] Call stack trace:
L 03/09/2019 - 21:35:16: [SM]   [0] CloseHandle
L 03/09/2019 - 21:35:16: [SM]   [1] Line 66, deathrun/menu.sp::mJoker

**Comment by Javierko** [comment]
Which options are wrong?

**Comment by m1000rr** [comment]
Well the menu actually not updating in real time. For example if you are batman and keep toggling between bhop/double jump they are showing in menu. But if you are joker and type !joker it is showing bhop and if you click on it it doesn't change instantly only prints to chat that you turned on speed.

**Comment by Javierko** [comment]
Finally [there](https://github.com/Javierko/DeathrunCSGO/commit/989f61b02f7772126aa8ba0ff9f4f226b8675dee) it is.

**Comment by m1000rr** [comment]
Ok thank You. The menu looks good so far. Will be moving forward for more testing.

**Comment by Javierko** [comment]
Okay, if there will be any more bugs, create a new issue, thanks.
